### ISSUE TITLE
Missing files when reproducing openvino results

### ISSUE THREAD

**Issue by mlosab3** [mlcommons/inference_results_v0.7#7]
Hello!
I am using openvino inference engine and I saw several submissions. I tried to reproduce [these results](https://github.com/mlperf/inference_results_v0.7/tree/master/closed/DellEMC/code/resnet50/openvino-loadgen-v0.7-drop) but could not find *ck-openvino-private.20200915.zip* anywhere. Can someone provide a link to this file please?
Thank you so much for this great effort!

**Comment by psyhtest** [comment]
Hi @mlosab3, thank you for your interest!

We (at [dv/dt](http://dividiti.com)) produced these results in collaboration with Dell and Intel. Since we only had limited time, we did not produce a compete workflow that could be used to build everything (libraries, models, etc.) from scratch like we did for [Intel's v0.5 submission](https://github.com/ctuning/ck-openvino). Instead, we provided CK wrappers around prebuilt binaries provided by Intel. While I can open-source the wrappers, they are useless without the binaries. Alas, I'm not at liberty to distribute the binaries.

I'm very keen to provide automated and reproducible CK workflows for the latest OpenVINO version, which could be used to reproduce Intel's v0.7 submission and help the community prepare future submissions. Unfortunately, I cannot make any promises right now to when it would become available. I will talk to Intel colleagues to see if they would be interested to collaborate on this.

For now, it would be helpful if you could explain why did you try to reproduce the OpenVINO results via CK, not via the [official Intel submission](https://github.com/mlperf/inference_results_v0.7/blob/master/closed/Intel/code/resnet/resnet-ov/README.md)?

**Comment by mlosab3** [comment]
Hello @psyhtest, thank you for your answer. I am a fan of automation and I follow the [CK project](https://github.com/ctuning/ck) with great interest. I am looking forward to seeing more workflows in the future!
